id = "zx"
name = "ZX"
description = "ZX support."
version = "0.0.1-dev.278"
schema_version = 1
authors = ["Nurul Huda (Apon) <me@nurulhudaapon.com>"]
repository = "https://github.com/nurulhudaapon/zx"

[language_servers.zls]
name = "zls"
language = "ZX"

[grammars.zx]
repository = "https://github.com/nurulhudaapon/zx"
path = "tree-sitter-zx"
commit = "f3faf77d22ccf730cefd239730f96be7e1905d38"

[debug_locators.zx-locator]
