[[language]]
name = "ziex"
language-id = "zx"
scope = "source.zx"
roots = ["build.zig", "zls.json", ".git"]
file-types = ["zx"]
grammar = "zx"
language-servers = ["zls"]

[[grammar]]
name = "zx"
source = { git = "https://github.com/nurulhudaapon/ziex", rev = "main", subpath = "pkg/tree-sitter-zx" }

# Optional: use the diagnostic filter proxy
#
# [language-server.zls-zx]
# command = "~/.config/helix/scripts/zls-zx-proxy"
# args = ["zls"]
#
# [[language]]
# name = "ziex"
# language-servers = ["zls-zx"]
